version: '3'

services:
  lb:
    image: haproxy
    ports:
      - "9050:8080"
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.40.0.2 # Assign a static IP address to the lb service
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  fablobusiness1:
    image: fablobusiness
    environment:
      - APPID=1111
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.40.0.3 # Assign a static IP address to fablobusiness1

  fablobusiness2:
    image: fablobusiness
    environment:
      - APPID=2222
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.40.0.4 # Assign a static IP address to fablobusiness2

  fablobusiness3:
    image: fablobusiness
    environment:
      - APPID=3333
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.40.0.5 # Assign a static IP address to fablobusiness3

  fablobusiness4:
    image: fablobusiness
    environment:
      - APPID=4444
    restart: always
    networks:
      marketplace:
        ipv4_address: 172.40.0.6 # Assign a static IP address to fablobusiness4

networks:
  marketplace:
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16 # Define a subnet for your custom network named "marketplace"
